import DownloadPdfButton from './DownloadPdfButton'
import { getReport, customers } from '@/lib/reportMetrics'

function Delta({ value, suffix = '' }: { value: number | null; suffix?: string }) {
  if (value === null) return <span className="muted">—</span>
  const up = value >= 0
  return <span className={up ? 'delta up' : 'delta down'}>{up ? '↑' : '↓'} {up ? '+' : ''}{value}{suffix}</span>
}
function Kpi({ label, value, delta, tone }: { label: string; value: string; delta?: React.ReactNode; tone?: string }) {
  return <div className={`card kpi ${tone ?? ''}`}><p className="eyebrow">{label}</p><strong>{value}</strong><div>{delta}</div></div>
}
function ConfidenceBadge({ value }: { value: string }) { return <span className={`badge confidence ${value.toLowerCase()}`}>Confidence: {value}</span> }
function SeverityBadge({ value }: { value: string }) { return <span className={`badge severity ${value.toLowerCase().replace(' ', '-')}`}>{value}</span> }
function PieChart({ slices }: { slices: Array<{ mood: string; pct: number; color: string; count: number }> }) {
  let start = 0
  const gradient = slices.map((s) => { const end = start + s.pct; const seg = `${s.color} ${start}% ${end}%`; start = end; return seg }).join(', ')
  return <div className="pie-wrap"><div className="pie" style={{ background: `conic-gradient(${gradient})` }}><span>{slices.reduce((a, b) => a + b.count, 0)}<small>responses</small></span></div><div className="legend">{slices.map((s) => <div key={s.mood}><i style={{ background: s.color }} />Mood {s.mood}: <strong>{s.pct}%</strong></div>)}</div></div>
}

export default function Home({ searchParams }: { searchParams?: { month?: string } }) {
  const customer = customers[0]
  const report = getReport(customer.id, searchParams?.month)
  const maxResponses = Math.max(...report.monthlyTrend.map((m) => m.responses))
  return <div className="shell"><header className="topbar"><div className="wrap"><div className="brand"><span className="mark">lp</span><span>Lollipop Monthly Reports<small>Executive Organizational Intelligence</small></span></div><form className="controls"><select name="month" defaultValue={report.month}>{customer.months.map((m) => <option key={m.month} value={m.month}>{m.label}</option>)}</select><button className="btn primary">Generate Report</button><DownloadPdfButton /></form></div></header><main className="wrap pages">

<section className="hero cover"><div className="card soft"><p className="eyebrow">A. Cover / Report Period</p><h1 className="title">Executive Workforce Intelligence</h1><p className="lede">{report.customerName} · {report.label}</p><div className="brief-meta"><span>{report.responseCount} responses</span><span>{report.reportConfidenceScore}/100 confidence</span><span>{report.healthSummary.rating}</span><span>{report.retentionRisk} retention risk</span></div></div><div className="card"><p className="eyebrow">B. Executive Intelligence Summary</p><h2>{report.strategicNarrative[0]}</h2><p>{report.strategicNarrative[1]}</p><p>{report.strategicNarrative[2]}</p><p><SeverityBadge value={report.healthSummary.rating} /> <span className={`badge ${report.retentionRisk !== 'Low' ? 'risk' : ''}`}>Retention Risk: {report.retentionRisk}</span> <ConfidenceBadge value={report.reportConfidence} /></p></div></section>

<section className="grid two section"><div className="card"><p className="eyebrow">C. Organizational Health Score</p><h2>{report.healthSummary.score}/100 · {report.healthSummary.rating}</h2><p>{report.healthSummary.reason}</p><div className="component-list">{report.healthSummary.components.map((c) => <div key={c.label}><strong>{c.label}</strong><span>{c.score}</span><p>{c.note}</p></div>)}</div></div><div className="card"><p className="eyebrow">D. Key Metrics Dashboard</p><div className="grid kpis mini"><Kpi label="Avg Mood" value={report.avgMood.toFixed(2)} delta={<Delta value={report.avgMoodChange} />}/><Kpi label="Positive" value={`${report.positivePct}%`} delta={<Delta value={report.positiveChange} suffix=" pts" />}/><Kpi label="Engagement" value={`${report.engagementScore}`} delta={`${report.responseCount} responses`}/><Kpi label="Confidence" value={`${report.reportConfidenceScore}`} delta={report.reportConfidence}/></div></div></section>

<section className="card section"><div className="page-label"><strong>E. What Changed This Period</strong><span>Meaningful movement vs weak signals</span></div><div className="change-grid">{report.whatChanged.map((c) => <div className="change-card" key={c.title}><div className="page-label"><strong>{c.title}</strong><SeverityBadge value={c.severity} /></div><p>{c.detail}</p><p className="muted"><strong>Interpretation:</strong> {c.meaning}</p><ConfidenceBadge value={c.confidence} /></div>)}</div></section>

<section className="card section"><div className="page-label"><strong>F. Company-Wide Sentiment Trends</strong><span>Internal benchmarks</span></div><div className="trend">{report.monthlyTrend.map((m) => <div className="trend-col" key={m.label}><i style={{ height: `${Math.max(30, (m.responses / maxResponses) * 160)}px` }} /><strong>{m.label}</strong><span>{m.avgMood.toFixed(2)} · {m.responses}</span></div>)}</div><div className="insight-grid"><p><strong>Trailing 3-month avg:</strong> {report.trend.threeMonthAvgMood ?? 'n/a'}</p><p><strong>Rolling positive:</strong> {report.trend.rollingPositivePct ?? 'n/a'}%</p><p><strong>Best / worst:</strong> {report.trend.bestMonth} / {report.trend.worstMonth}</p><p><strong>Persistence:</strong> {report.trend.meaningfulMovement}</p></div></section>

<section className="grid two section"><div className="card"><p className="eyebrow">G. Engagement Quality Analysis</p><h2>Participation is directionally useful, but denominator-limited.</h2><p><strong>Unique participants:</strong> {report.engagement.uniqueParticipants}</p><p><strong>Response rate:</strong> {report.engagement.responseRate ?? 'Unavailable — eligible population not provided'}</p><p><strong>Participation change:</strong> <Delta value={report.engagement.participationChange} /> responses</p><p><strong>Silent population risk:</strong> {report.engagement.silentPopulationRisk}</p><p className="muted">Engagement quality matters because a high score from a narrow group can mask silent-team risk, while high participation with low mood is a stronger operational warning.</p><ConfidenceBadge value={report.engagement.confidence} /></div><div className="card"><p className="eyebrow">H. Emotional Wellness & Theme Analysis</p><h2>Emotion Mix</h2>{report.topEmotions.slice(0,6).map((e) => <div key={e.emotion}><p>{e.emotion}: {e.count}</p><div className="bar"><i style={{ width: `${e.pct}%` }} /></div></div>)}<PieChart slices={report.moodDistribution} /></div></section>

<section className="grid two section"><div className="card"><div className="page-label"><strong>I. AI Comment Analysis</strong><ConfidenceBadge value={report.commentIntelligence.confidence} /></div><h2>What the comments reveal</h2><p>{report.commentIntelligence.revealing}</p><div className="theme-grid"><div><strong>Work-related</strong><span>{report.commentIntelligence.workRelatedCount}</span></div><div><strong>Wellbeing</strong><span>{report.commentIntelligence.wellbeingCount}</span></div><div><strong>Positive</strong><span>{report.commentIntelligence.positiveCount}</span></div><div><strong>Stress/Burnout</strong><span>{report.commentIntelligence.stressBurnoutCount}</span></div><div><strong>Recognition</strong><span>{report.commentIntelligence.recognitionCount}</span></div><div><strong>Leadership/Comm.</strong><span>{report.commentIntelligence.leadershipCommunicationCount}</span></div></div></div><div className="card"><h2>Comment Themes & Anonymized Examples</h2><div className="list">{report.commentIntelligence.themes.map((t) => <div className="rec" key={t.theme}><strong>{t.theme} <span className="muted">({t.count})</span></strong><p>{t.signal}</p></div>)}</div><ul className="list compact">{report.commentIntelligence.representativeComments.map((c) => <li key={c}>{c}</li>)}</ul></div></section>

<section className="card section"><div className="page-label"><strong>J. Team-Level Intelligence</strong><span>Interpretation, not raw rankings</span></div><div className="team-grid">{report.teamIntelligence.map((t) => <div className="team-card" key={t.team}><div className="page-label"><strong>{t.team}</strong><SeverityBadge value={t.severity} /></div><p><strong>Mood:</strong> {t.avgMood.toFixed(2)} <Delta value={t.change} /> · <strong>Participation:</strong> {t.responses} (<Delta value={t.participationTrend} />)</p><p><strong>Distribution:</strong> {t.positivePct}% positive · {t.neutralPct}% neutral · {t.negativePct}% negative</p><p><strong>Read:</strong> {t.keyConcernOrStrength}</p><p><strong>Manager action:</strong> {t.managerAction}</p>{t.commentThemes.length > 0 && <p className="muted"><strong>Themes:</strong> {t.commentThemes.join(', ')}</p>}{t.privacyNote && <p className="muted"><strong>Privacy:</strong> {t.privacyNote}</p>}<ConfidenceBadge value={t.confidence} /></div>)}</div></section>

<section className="grid two section"><div className="card"><p className="eyebrow">K. Risk / Watchlist Areas</p><div className="list">{report.riskWatchlist.map((r) => <div className="rec" key={r.title}><strong>{r.title} <SeverityBadge value={r.severity} /></strong><p>{r.signal}</p><p><strong>Recommended action:</strong> {r.recommendedAction}</p><ConfidenceBadge value={r.confidence} /></div>)}</div></div><div className="card"><p className="eyebrow">L. Positive Momentum / What’s Working</p><div className="list">{report.positiveMomentum.map((r) => <div className="rec" key={r.title}><strong>{r.title} <SeverityBadge value={r.severity} /></strong><p>{r.signal}</p><p><strong>Preserve / replicate:</strong> {r.recommendedAction}</p><ConfidenceBadge value={r.confidence} /></div>)}</div></div></section>

<section className="card section"><div className="page-label"><strong>M. Recommended Leadership Actions</strong><span>Manager-ready and tied to evidence</span></div><div className="action-grid">{report.recommendations.map((r) => <div className="rec action" key={r.title}><strong><span className="priority">{r.priority}</span> {r.title}</strong><p className="muted">Owner: {r.owner} · Urgency: {r.urgency} · Impact: {r.impact} · Difficulty: {r.difficulty}</p><p><strong>Action:</strong> {r.nextStep}</p><p><strong>Expected outcome:</strong> {r.why}</p><ConfidenceBadge value={r.confidence} /></div>)}</div></section>

<section className="grid two section"><div className="card"><p className="eyebrow">N. Optional Manager Report Outputs</p><h2>Scoped team-only reports are supported in the report model.</h2><p>{report.managerReport.description}</p><p><strong>Eligible team reports:</strong> {report.managerReport.eligibleTeams.join(', ') || 'None yet'}</p><p><strong>Sample-warning teams:</strong> {report.managerReport.sampleWarningTeams.join(', ') || 'None'}</p><ul className="list compact">{report.managerReport.safeguards.map((s) => <li key={s}>{s}</li>)}</ul></div><div className="card"><p className="eyebrow">O. Data Quality & Confidence Notes</p><h2>{report.reportConfidenceScore}/100 · {report.reportConfidence}</h2><p>{report.confidenceRationale}</p><p><strong>Unique participants:</strong> {report.engagement.uniqueParticipants}</p><p><strong>Low-sample teams:</strong> {report.lowConfidenceTeams.length ? report.lowConfidenceTeams.map((t) => t.team).join(', ') : 'None'}</p><p className="muted">Conclusions are strongest when mood, comments, participation, and trend direction all point to the same signal. Small-team findings should be treated as directional until more responses are collected.</p></div></section>

<section className="card section"><p className="eyebrow">P. Appendix / Methodology Improvements</p><ul className="list">{report.improvements.map((i) => <li key={i}>{i}</li>)}</ul><p className="muted">Recommended next product upgrades: external benchmarks by industry, manager drill-down routing, comment topic model with human review, retention-risk calibration, and a one-page CEO brief followed by appendix detail.</p></section>

</main></div>
}
