import { getReport, customers } from '@/lib/reportMetrics'

function Delta({ value, suffix = '' }: { value: number | null; suffix?: string }) {
  if (value === null) return <span className="muted">—</span>
  const up = value >= 0
  return <span className={up ? 'delta up' : 'delta down'}>{up ? '↑' : '↓'} {up ? '+' : ''}{value}{suffix}</span>
}
function Kpi({ label, value, delta, tone }: { label: string; value: string; delta?: React.ReactNode; tone?: string }) {
  return <div className={`card kpi ${tone ?? ''}`}><p className="eyebrow">{label}</p><strong>{value}</strong><div>{delta}</div></div>
}

export default function Home({ searchParams }: { searchParams?: { month?: string } }) {
  const customer = customers[0]
  const report = getReport(customer.id, searchParams?.month)
  const maxResponses = Math.max(...report.monthlyTrend.map((m) => m.responses))
  return <div className="shell"><header className="topbar"><div className="wrap"><div className="brand"><span className="mark">lp</span><span>Lollipop Monthly Reports<small>Reusable executive workforce intelligence generator</small></span></div><form className="controls"><select name="month" defaultValue={report.month}>{customer.months.map((m) => <option key={m.month} value={m.month}>{m.label}</option>)}</select><button className="btn primary">Generate Report</button><button className="btn" type="button">PDF export next</button></form></div></header><main className="wrap pages"><section className="hero"><div className="card soft"><p className="eyebrow">Report Generator Demo · {report.label}</p><h1 className="title">Executive Workforce Intelligence</h1><p className="lede">Sample customer: <strong>{report.customerName}</strong>. Cosmo data is seeded only to validate spreadsheet imports, calculations, and report design for a reusable monthly reporting system.</p></div><div className="card"><p className="eyebrow">Executive Summary</p><h2>{report.executiveSummary}</h2><p><span className={`badge ${report.healthSeverity === 'Watch' ? 'watch' : ''}`}>{report.healthSeverity}</span> <span className={`badge ${report.retentionRisk !== 'Low' ? 'risk' : ''}`}>Retention Risk: {report.retentionRisk}</span></p></div></section>

<section className="section"><div className="page-label"><strong>Page 1</strong><span>30-second executive snapshot</span></div><div className="grid kpis"><Kpi label="Health Score" value={`${report.healthScore}`} delta={report.healthSeverity} tone="green"/><Kpi label="Avg Mood" value={report.avgMood.toFixed(2)} delta={<Delta value={report.avgMoodChange} />}/><Kpi label="Positive Sentiment" value={`${report.positivePct}%`} delta={<Delta value={report.positiveChange} suffix=" pts" />}/><Kpi label="Engagement Score" value={`${report.engagementScore}`} delta={`${report.responseCount} responses`}/><Kpi label="Follow-ups" value={`${report.followUpRequests}`} delta={report.followUpCompletionPct === null ? 'No requests recorded' : `${report.followUpCompletionPct}% complete`} tone="amber"/></div></section>

<section className="grid two section"><div className="card"><h2>Leadership Attention Required</h2><ol className="list">{report.leadershipAttention.map((item) => <li key={item}>{item}</li>)}</ol></div><div className="card"><h2>Recommended Actions</h2><div className="list">{report.recommendations.map((r) => <div className="rec" key={r.title}><strong>{r.title}</strong><p className="muted">Urgency: {r.urgency} · Impact: {r.impact} · Difficulty: {r.difficulty}</p><p>{r.action}</p></div>)}</div></div></section>

<section className="grid two section"><div className="card"><h2>Top Teams</h2><table className="table"><tbody>{report.topTeams.map((t) => <tr key={t.team}><td><strong>{t.team}</strong></td><td>{t.avgMood.toFixed(2)}</td><td><Delta value={t.change} /></td></tr>)}</tbody></table></div><div className="card"><h2>Watch Teams</h2><table className="table"><tbody>{report.watchTeams.map((t) => <tr key={t.team}><td><strong>{t.team}</strong>{t.sampleWarning && <div className="muted">Low sample size</div>}</td><td>{t.avgMood.toFixed(2)}</td><td><span className="badge watch">{t.risk}</span></td></tr>)}</tbody></table></div></section>

<section className="card section"><div className="page-label"><strong>Page 2</strong><span>Organizational trends</span></div><h2>Month-by-Month Trend</h2><div className="trend">{report.monthlyTrend.map((m) => <div className="trend-col" key={m.label}><i style={{ height: `${Math.max(30, (m.responses / maxResponses) * 160)}px` }} /><strong>{m.label}</strong><span>{m.avgMood.toFixed(2)} · {m.responses}</span></div>)}</div></section>

<section className="grid two section"><div className="card"><div className="page-label"><strong>Page 3</strong><span>Team health matrix</span></div><h2>Team Comparison</h2><div className="table-wrap"><table className="table"><thead><tr><th>Team</th><th>Responses</th><th>Avg Mood</th><th>Positive</th><th>Risk</th></tr></thead><tbody>{report.allTeams.map((t) => <tr key={t.team}><td>{t.team}{t.sampleWarning && <div className="muted">Low sample</div>}</td><td>{t.responses}</td><td>{t.avgMood.toFixed(2)}</td><td>{t.positivePct}%</td><td>{t.risk}</td></tr>)}</tbody></table></div></div><div className="card"><h2>Mood Distribution</h2>{report.moodDistribution.map((m) => <div key={m.mood}><p>Mood {m.mood}: {m.pct}%</p><div className="bar"><i style={{ width: `${m.pct}%` }} /></div></div>)}</div></section>

<section className="grid two section"><div className="card"><div className="page-label"><strong>Page 4</strong><span>Emotional intelligence</span></div><h2>Top Emotions</h2>{report.topEmotions.map((e) => <div key={e.emotion}><p>{e.emotion}: {e.count}</p><div className="bar"><i style={{ width: `${e.pct}%` }} /></div></div>)}</div><div className="card"><h2>Comment Intelligence</h2><p className="muted">Comment classification will become AI-assisted. V1 shows anonymized themes only and avoids raw personal detail.</p><ul className="list">{report.comments.slice(0,4).map((c, i) => <li key={i}>{c.length > 150 ? `${c.slice(0,150)}…` : c}</li>)}</ul></div></section>

<section className="grid two section"><div className="card"><div className="page-label"><strong>Page 5</strong><span>Responsiveness & data quality</span></div><h2>Leadership Responsiveness</h2><p>{report.followUpRequests === 0 ? 'No follow-up requests were recorded in the selected month. Responsiveness scoring is marked provisional until follow-up status data is consistently populated.' : `${report.followUpRequests} follow-up requests recorded.`}</p><p className="muted">Unsubscribed records in demo set for this customer: {report.unsubscribedCount}</p></div><div className="card"><h2>Product Improvements</h2><ul className="list">{report.improvements.map((i) => <li key={i}>{i}</li>)}</ul></div></section>
<p className="print-note">Next build: spreadsheet upload UI, PDF export, AI narrative generation, customer management, and direct data integration.</p></main></div>
}
